### ISSUE TITLE
How to connect to RPC interface?

### ISSUE THREAD

**Issue by loganmarchione** [lncm/docker-bitcoind#46]
I'm trying to write a bash script to connect to the RPC interface via curl. I have port 8332 open, but I don't see any documentation for how to setup a RPC user/password. Am I missing something?

Also, I don't see a `bitcoin.conf` file anywhere either. I was just going to bind-mount one manually. Is this the suggested way?

**Comment by nolim1t** [comment]
Hi,

Please refer to [this project](https://github.com/lncm/thebox-compose-system) which has a lot of [config samples](https://github.com/lncm/thebox-compose-system/blob/master/bitcoin/bitcoin.conf).

Please not that configuration is controlled through [this script](https://github.com/lncm/thebox-compose-system/blob/master/configure-box.sh) also.

Hopefully the above helps you?

**Comment by loganmarchione** [comment]
So does that mean I can't use RPC in lncm/docker-bitcoind?

**Comment by nolim1t** [comment]
you can use whatever bitcoind has allowed.

**Comment by loganmarchione** [comment]
Got it, thanks!
