### ISSUE TITLE
Optimize C flags

### ISSUE THREAD

**Issue by AaronDewes** [lncm/docker-bitcoind#47]
Removing the debug info like https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#memory-requirements makes the compile use less memory and potentially faster, as well as reducing the final size a bit. @nolim1t Can you add this when releasing 0.22?

**Comment by nolim1t** [comment]
Thanks I'll take a look.

Maybe the next version of 0.21.X I'll consider adding those switches.

**Comment by nolim1t** [comment]
Hi, please try `lncm/bitcoind:v0.21.0-arm64v8-build21`

I've also included in the sqlite stuff too

**Comment by AaronDewes** [comment]
Thanks, I'll try it.
