### ISSUE TITLE
Compile in SQLite support

### ISSUE THREAD

**Issue by lukechilds** [lncm/docker-bitcoind#50]
It seems like these builds don't compile in support for SQLite which is required for descriptor wallets.

This causes issues when using these builds with Specter: https://github.com/cryptoadvance/specter-desktop/issues/980

Is there any reason it's not included? Can we add it if not?

Also maybe it would be better to use the pre-built signed release binaries in these images, that way there will be less surprises, more reliable behaviour, and the logic will also be better tested.

**Comment by nolim1t** [comment]
No reason why it wasn't there or unaware of the new feature of specter desktop using it. I'll take a look at this.

I think just keeping the build images the way it is

**Comment by lukechilds** [comment]
@nolim1t are these images live now?
