### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by kroese** [lncm/docker-bitcoind#66]
The container does not seem to have IPv6 support. When I try to ping an IPv6 address from within the container I get: 

`ping: sendto: Address not available`

**Comment by nolim1t** [comment]
It does but you have to use host networking.

I use ipv6 with this

**Comment by nolim1t** [comment]
I don't see why not but its more a docker specific configuration.

If the bridge networking gives you an IPv6 address then bitcoind will use that.
