### ISSUE TITLE
bitcoin data saving to /root/.bitcoin instead of /data/.bitcoin

### ISSUE THREAD

**Issue by tensor5g** [lncm/docker-bitcoind#85]
Documentation suggests that the bitcoin chain is being saved to /data/.bitcoin but in reality it's being saved to /root/.bitcoin, at least when using user: 0:0 in the docker compose file. If this is intended behavior, documentation should be updated.

**Comment by nolim1t** [comment]
If you're using 0:0 then it is indeed ```/root/.bitcoin```

The folder ```/data/.bitcoin``` is within the container, which we normally expose via a mapping and normally we use 1000:1000 (default user), however you can change everything to whatever you wish

**Comment by tensor5g** [comment]
So the documentation is misleading: https://github.com/lncm/docker-bitcoind/blob/98c08e1c00243cbebb34f3019e2c2eef30e79910/README.md?plain=1#L158-L175

this example from readme.md would never work

**Comment by nolim1t** [comment]
oh yeah that probably needs to be updated. Thanks for that.

Will probably replace it with a veriation of https://github.com/lncm/thebox-compose-system/blob/master/docker-compose.yml (which is essentially the first iteration of what Umbrel and RunCitadel is today)

**Comment by SK-StYleZ** [comment]
ran into same issue, created a pr https://github.com/lncm/docker-bitcoind/pull/86
